### ISSUE TITLE
Question: No Value Arg

### ISSUE THREAD

**Issue by korman** [clibs/flag#10]
If cmd like this:

"xxxx --param1"

No value,Only name.

How read this flag?

**Comment by jwerle** [comment]
@korman try [`flagset_bool`](https://github.com/clibs/flag/blob/master/flag.h#L89) or [`flag_bool`](https://github.com/clibs/flag/blob/master/flag.h#L106)

**Comment by stephenmathieson** [comment]
@jwerle is right, use the boolean functions for this. Closing for now. Feel free to reopen if `flag_bool` isn't what you were looking for.
